qwen_2.5:
  client_kwargs:
    api_key: ""
    base_url:
  generation:
    max_tokens: 4096
    temperature: 0.0
    stream: true

ollama:
  embedding_url: "http://localhost:11434/api/embeddings"
  model_name: "nomic-embed-text:latest"
  embedding_dim: 768
