deepseek-v3.2:
  use_responses_api: true
  client_kwargs:
    api_key: ""
    base_url: ""
  generation:
    max_tokens: 16000
    temperature: 0.0
    stream: true

ollama:
  embedding_url: "http://localhost:11434/api/embeddings"
  model_name: "nomic-embed-text:latest"
  embedding_dim: 768
